version: '3.5'

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    volumes:
      - ./infrastructure/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./infrastructure/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
    ports:
      - '3000:3000'

  golang:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: go-skeleton-golang
    restart: always
    ports:
      - '8080:8080'

volumes:
  prometheus:
    name: prometheus
  grafana-storage:
    name: grafana-storage
