{
 "title": "Golang HTTP",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(http_response_time_seconds_sum/http_response_time_seconds_count)"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "response_status" }
   ]
  },
  {
   "title": "Requests total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  }
 ]
}